# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sports-talk-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sports-talk
  template:
    metadata:
      labels:
        app: sports-talk
    spec:
      containers:
        - name: sports-talk-container
          image: montredavis/sports-talk:latest  # or your Docker Hub image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "1000m"
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: sports-talk-service
spec:
  selector:
    app: sports-talk
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP